### ISSUE TITLE
setState() called after dispose(): _ProgressiveImageState#0cffa(lifecycle state: defunct, not mounted)

### ISSUE THREAD

**Issue by Gursewak-Uppal** [InvincibleZeal/progressive_image#3]
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.

The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

When the exception was thrown, this was the stack: 
#0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1112:9)
#1      State.setState (package:flutter/src/widgets/framework.dart:1147:6)
#2      _ProgressiveImageState._updateProgress (package:progressive_image/progressive_image.dart:333:5)
#3      _ProgressiveImageState.initState.<anonymous closure> (package:progressive_image/progressive_image.dart:362:9)
#4      ImageStreamCompleter.setImage (package:flutter/src/painting/image_stream.dart:407:18)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by image resource service ════════════════════════════════════════════
setState() called after dispose(): _ProgressiveImageState#f4cc4(lifecycle state: defunct, not mounted)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (3) Exception caught by image resource service ════════════════════════════════════════════
setState() called after dispose(): _ProgressiveImageState#22353(lifecycle state: defunct, not mounted)

**Comment by InvincibleZeal** [comment]
Fixed in `v1.0.1`
