### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by hatemragab** [InvincibleZeal/progressive_image#7]
Null safety Support

**Comment by cerberodev** [comment]
> Null safety Support

I can work on this, by April 2nd.

Cc: @InvincibleZeal

**Comment by InvincibleZeal** [comment]
> > Null safety Support
> 
> I can work on this, by April 2nd.
> 
> Cc: @InvincibleZeal 

Please go ahead.

**Comment by Dosenbiiir** [comment]
Null support would be great :) thanks

**Comment by rahulrkhot** [comment]
Please Provide Support for null safety
