### ISSUE TITLE
[FEATURE REQUEST] add error handling 

### ISSUE THREAD

**Issue by Tom3652** [InvincibleZeal/progressive_image#9]
Hello and thanks for the package !

The only missing attribute would be ```onError``` so that we can display something in case it doesn't load. 
So far the only package that does this is ```CachedNetworkImage``` widget. 
However i can't use the cache system in my case so i can't use it and have no error handling... 

Thanks in advance !

**Comment by InvincibleZeal** [comment]
If you have any specific implementation in mind, I can assign you and you can work on it.

**Comment by Tom3652** [comment]
I wish i had the time... But actually Image.network does handle the error as well so it's fine.
